name: estatex
description: "A Verified Real Estate Marketplace with Smart Bidding."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.7 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # --- SRS অনুযায়ী প্রয়োজনীয় প্যাকেজ ---
  supabase_flutter: ^2.0.2     # ব্যাকএন্ড এবং অথেনটিকেশনের জন্য
  google_fonts: ^6.1.0         # প্রিমিয়াম ফন্ট ব্যবহারের জন্য
  flutter_svg: ^2.0.9          # এসভিজি আইকন ব্যবহারের জন্য
  image_picker: ^1.0.7         # প্রপার্টি ইমেজ আপলোডের জন্য
  provider: ^6.1.1             # স্টেট ম্যানেজমেন্টের জন্য
  flutter_spinkit: ^5.2.0      # স্প্ল্যাশ স্ক্রিনে সুন্দর লোডিংয়ের জন্য

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # এসেট ফোল্ডার ডিক্লেয়ারেশন
  assets:
    - assets/images/
    - assets/icons/